server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/stockhelper?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: com.kodomo.stockhelper.config.CustomMysqlDialect
    open-in-view: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true


stockhelper:
  initialDataLimit: 20
  initialDataSource: NetEaseInitializationHttpRequestHelper
  maSegment: 5,10,30,60,120
  recommendedMinTurnOverRate: 1.0