server:
  port: 80
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: com.kodomo.stockhelper.config.CustomMysqlDialect
    open-in-view: true
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          batch_versioned_data: true
          order_inserts: true
        enable_lazy_load_no_trans: true

---
spring:
  profiles: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/stockhelper?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8

stockhelper:
  initialDataLimit: 100
  initialDataSource: NetEaseInitializationHttpRequestHelper
  maSegment: 5,10,30,60,120
  recommendedMinTurnOverRate: 1.0

---
spring:
  profiles: prod
  datasource:
    username: kdm
    password: stockhelper%
    url: jdbc:mysql://localhost:3306/stockhelper?characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT%2B8

stockhelper:
  initialDataLimit: 999999
  initialDataSource: NetEaseInitializationHttpRequestHelper
  maSegment: 5,10,30,60,120
  recommendedMinTurnOverRate: 1.0